apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kcontext-cluster-meta
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kcontext-cluster-meta
subjects:
  - kind: ServiceAccount
    name: kcontext
    namespace: kcontext
