apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kcontext-cluster-meta
rules:
  - apiGroups: [""]
    resources: [nodes]
    verbs: [list]
  - apiGroups: [config.openshift.io]
    resources: [clusterversions]
    verbs: [get, list]
